export type CandidateCategory =
  | "software-development"
  | "virtual-assistant"
  | "finance-accounting"
  | "digital-marketing"
  | "legal-compliance"
  | "healthcare-rcm"
  | "customer-support"
  | "cybersecurity"
  | "design"
  | "content-seo";

export type Candidate = {
  id: string;
  name: string;
  role: string;
  category: CandidateCategory;
  experience: string;
  rate: string;
  skills: string[];
  timezone: string;
  availability: "immediate" | "1-week" | "2-weeks";
  highlights: string;
  aiTools: string[];
};

export const candidateCategoryLabels: Record<CandidateCategory, string> = {
  "software-development": "Software Development",
  "virtual-assistant": "Virtual Assistant",
  "finance-accounting": "Finance & Accounting",
  "digital-marketing": "Digital Marketing",
  "legal-compliance": "Legal & Compliance",
  "healthcare-rcm": "Healthcare & RCM",
  "customer-support": "Customer Support",
  cybersecurity: "Cybersecurity & IT",
  design: "Graphic Design",
  "content-seo": "Content & SEO",
};

/* ─── All 120 candidate profiles (anonymized) ─── */
export const allCandidates: Candidate[] = [
  /* ════════════════════════════════════════════════
     SOFTWARE DEVELOPMENT (dev-001 to dev-012)
     ════════════════════════════════════════════════ */
  {
    id: "dev-001",
    name: "Karthik R.",
    role: "Senior Full-Stack Developer",
    category: "software-development",
    experience: "8 years",
    rate: "$13/hr",
    skills: ["React", "Node.js", "TypeScript", "AWS", "PostgreSQL", "Docker"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Built SaaS platforms for 3 US startups. Led a 6-person dev team delivering a fintech dashboard processing $2M+ daily transactions.",
    aiTools: ["GitHub Copilot", "Claude", "Cursor"],
  },
  {
    id: "dev-002",
    name: "Divya N.",
    role: "Frontend Developer",
    category: "software-development",
    experience: "5 years",
    rate: "$10/hr",
    skills: ["React", "Next.js", "Tailwind CSS", "TypeScript", "Figma-to-Code", "Jest"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Specialized in pixel-perfect React UIs. Converted 40+ Figma designs to production code for e-commerce and healthcare clients.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "dev-003",
    name: "Suresh P.",
    role: "Backend Developer",
    category: "software-development",
    experience: "6 years",
    rate: "$11/hr",
    skills: ["Python", "Django", "REST APIs", "PostgreSQL", "Redis", "Celery"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Designed microservices architecture handling 500K+ API calls/day. Built payment integrations with Stripe and PayPal for 2 US SaaS products.",
    aiTools: ["GitHub Copilot", "Claude"],
  },
  {
    id: "dev-004",
    name: "Lakshmi G.",
    role: "Mobile Developer",
    category: "software-development",
    experience: "4 years",
    rate: "$9/hr",
    skills: ["React Native", "Flutter", "Firebase", "iOS", "Android", "GraphQL"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Published 8 mobile apps on App Store and Play Store. Built a delivery tracking app with 50K+ downloads for a US logistics company.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "dev-005",
    name: "Harish M.",
    role: "DevOps Engineer",
    category: "software-development",
    experience: "7 years",
    rate: "$12/hr",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Docker", "Linux"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "AWS Solutions Architect certified. Reduced cloud costs by 40% for a Series B startup. Managed infrastructure for 3 production SaaS products.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "dev-006",
    name: "Tanya S.",
    role: "QA Engineer",
    category: "software-development",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Selenium", "Cypress", "Jest", "API Testing", "Postman", "JIRA"],
    timezone: "EST / CST flexible",
    availability: "1-week",
    highlights: "Built automated test suites covering 95% code coverage for a healthtech platform. Reduced production bugs by 60% through CI-integrated testing.",
    aiTools: ["ChatGPT", "Cursor"],
  },
  {
    id: "dev-007",
    name: "Manish K.",
    role: "Data Engineer",
    category: "software-development",
    experience: "6 years",
    rate: "$11/hr",
    skills: ["Python", "Apache Spark", "Airflow", "Snowflake", "SQL", "ETL Pipelines"],
    timezone: "GMT / AEST flexible",
    availability: "2-weeks",
    highlights: "Built real-time data pipelines processing 10M+ records/day for a US e-commerce company. Expert in Snowflake and dbt transformations.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "dev-008",
    name: "Swathi V.",
    role: "Full-Stack Developer",
    category: "software-development",
    experience: "4 years",
    rate: "$9/hr",
    skills: ["Vue.js", "Node.js", "MongoDB", "Express", "Tailwind CSS", "Git"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Delivered 5 full-stack web apps for US small businesses. Specializes in MEVN stack with real-time features using Socket.io.",
    aiTools: ["GitHub Copilot", "Claude"],
  },
  {
    id: "dev-009",
    name: "Nitin J.",
    role: "Cloud Architect",
    category: "software-development",
    experience: "9 years",
    rate: "$14/hr",
    skills: ["AWS", "Azure", "Microservices", "Serverless", "CloudFormation", "Security"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Architected multi-region AWS infrastructure for a US fintech with 99.99% uptime. Holds both AWS and Azure certifications.",
    aiTools: ["GitHub Copilot", "ChatGPT", "Claude"],
  },
  {
    id: "dev-010",
    name: "Bhavana L.",
    role: "Frontend Developer",
    category: "software-development",
    experience: "3 years",
    rate: "$8/hr",
    skills: ["React", "TypeScript", "Storybook", "CSS Modules", "Accessibility", "Webpack"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Built WCAG 2.1 compliant component libraries for 2 enterprise clients. Strong focus on accessible, performant UI development.",
    aiTools: ["Cursor", "ChatGPT"],
  },
  {
    id: "dev-011",
    name: "Prasad T.",
    role: "Backend Developer",
    category: "software-development",
    experience: "7 years",
    rate: "$12/hr",
    skills: ["Java", "Spring Boot", "Kafka", "MySQL", "Docker", "REST APIs"],
    timezone: "EST / GMT flexible",
    availability: "2-weeks",
    highlights: "Built enterprise-grade Java microservices for 2 Fortune 500 clients. Integrated Kafka event streaming handling 1M+ events/hour.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "dev-012",
    name: "Isha D.",
    role: "Machine Learning Engineer",
    category: "software-development",
    experience: "5 years",
    rate: "$13/hr",
    skills: ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision", "MLOps"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Deployed 4 production ML models for US companies including a fraud detection system with 98.5% accuracy. Strong in NLP and recommendation engines.",
    aiTools: ["GitHub Copilot", "Claude", "ChatGPT"],
  },

  /* ════════════════════════════════════════════════
     VIRTUAL ASSISTANT (va-001 to va-012)
     ════════════════════════════════════════════════ */
  {
    id: "va-001",
    name: "Jyoti H.",
    role: "Executive Virtual Assistant",
    category: "virtual-assistant",
    experience: "6 years",
    rate: "$7/hr",
    skills: ["Calendar Management", "Email Management", "Travel Booking", "CRM", "Presentation Design", "Research"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Supported 4 C-suite executives at US companies. Manages complex multi-timezone calendars and coordinates board meetings.",
    aiTools: ["ChatGPT", "Claude", "Notion AI"],
  },
  {
    id: "va-002",
    name: "Farhan A.",
    role: "General Virtual Assistant",
    category: "virtual-assistant",
    experience: "3 years",
    rate: "$5/hr",
    skills: ["Data Entry", "Email Support", "Google Workspace", "Spreadsheets", "Customer Follow-ups", "File Management"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Handled admin operations for a US real estate agency and an e-commerce brand. Processes 200+ data entries daily with 99.5% accuracy.",
    aiTools: ["ChatGPT", "Canva"],
  },
  {
    id: "va-003",
    name: "Ritika B.",
    role: "Real Estate Virtual Assistant",
    category: "virtual-assistant",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["MLS Listings", "CRM Management", "Transaction Coordination", "Follow My Lead", "Zillow", "Lead Nurturing"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Managed listings and transactions for 3 US real estate teams. Coordinated 50+ closings and maintained CRM with 2,000+ contacts.",
    aiTools: ["ChatGPT", "Notion AI"],
  },
  {
    id: "va-004",
    name: "Amit G.",
    role: "E-commerce Virtual Assistant",
    category: "virtual-assistant",
    experience: "5 years",
    rate: "$7/hr",
    skills: ["Shopify", "Amazon Seller Central", "Inventory Management", "Order Processing", "Product Listings", "Customer Service"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Managed Shopify and Amazon stores for 5 US brands. Handled 300+ orders/week and maintained 4.8-star seller ratings.",
    aiTools: ["ChatGPT", "Canva AI"],
  },
  {
    id: "va-005",
    name: "Sunita W.",
    role: "Administrative Assistant",
    category: "virtual-assistant",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["Scheduling", "Document Preparation", "Meeting Notes", "Google Workspace", "Slack", "Project Coordination"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Provided admin support to a 20-person US marketing agency. Expert in Notion-based project tracking and meeting documentation.",
    aiTools: ["ChatGPT", "Notion AI", "Grammarly"],
  },
  {
    id: "va-006",
    name: "Rohan C.",
    role: "Research Assistant",
    category: "virtual-assistant",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["Market Research", "Competitive Analysis", "Data Collection", "Report Writing", "Google Sheets", "Presentation Design"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Conducted market research for 2 US consulting firms. Delivered 100+ research briefs covering competitor analysis and industry trends.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "va-007",
    name: "Pallavi J.",
    role: "Executive Virtual Assistant",
    category: "virtual-assistant",
    experience: "7 years",
    rate: "$8/hr",
    skills: ["Inbox Management", "Travel Coordination", "Board Decks", "Salesforce", "Expense Reports", "Confidential Filing"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Supported CEOs at 2 US tech startups through Series A and B rounds. Managed investor communications and due diligence documentation.",
    aiTools: ["Claude", "Notion AI", "ChatGPT"],
  },
  {
    id: "va-008",
    name: "Gaurav P.",
    role: "Bookkeeping Assistant",
    category: "virtual-assistant",
    experience: "3 years",
    rate: "$5/hr",
    skills: ["QuickBooks", "Invoice Processing", "Expense Tracking", "Bank Reconciliation", "Data Entry", "Google Sheets"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Assisted 8 US small businesses with basic bookkeeping and invoice processing. Maintained accurate records with zero discrepancies over 2 years.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "va-009",
    name: "Chitra M.",
    role: "Social Media Assistant",
    category: "virtual-assistant",
    experience: "2 years",
    rate: "$5/hr",
    skills: ["Content Scheduling", "Canva", "Instagram", "Facebook", "Hashtag Research", "Engagement Tracking"],
    timezone: "EST / CST flexible",
    availability: "2-weeks",
    highlights: "Managed social posting schedules for 6 US brands. Created 500+ graphics using Canva and maintained consistent posting calendars.",
    aiTools: ["ChatGPT", "Canva AI"],
  },
  {
    id: "va-010",
    name: "Tarun D.",
    role: "Lead Generation Assistant",
    category: "virtual-assistant",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["LinkedIn Prospecting", "Apollo.io", "Cold Email", "CRM Updates", "List Building", "Data Enrichment"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Built prospect lists totaling 50,000+ verified contacts for 4 US B2B companies. Achieved 35% email open rates on outbound campaigns.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "va-011",
    name: "Megha S.",
    role: "General Virtual Assistant",
    category: "virtual-assistant",
    experience: "2 years",
    rate: "$5/hr",
    skills: ["Data Entry", "Email Management", "Customer Queries", "Google Workspace", "Trello", "Basic Reporting"],
    timezone: "GMT / AEST flexible",
    availability: "1-week",
    highlights: "Supported operations for a US fitness brand and online tutoring company. Handles high-volume email triage and appointment scheduling.",
    aiTools: ["ChatGPT", "Grammarly"],
  },
  {
    id: "va-012",
    name: "Sahil R.",
    role: "Project Coordination Assistant",
    category: "virtual-assistant",
    experience: "5 years",
    rate: "$7/hr",
    skills: ["Asana", "Monday.com", "Meeting Coordination", "Status Reporting", "Stakeholder Communication", "SOPs"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Coordinated projects for a 30-person US software agency. Managed timelines, sprint reporting, and cross-team communication across 4 time zones.",
    aiTools: ["ChatGPT", "Notion AI", "Claude"],
  },

  /* ════════════════════════════════════════════════
     FINANCE & ACCOUNTING (fin-001 to fin-012)
     ════════════════════════════════════════════════ */
  {
    id: "fin-001",
    name: "Rajesh V.",
    role: "Senior Bookkeeper",
    category: "finance-accounting",
    experience: "8 years",
    rate: "$9/hr",
    skills: ["QuickBooks Online", "Xero", "Payroll", "Tax Prep", "AP/AR", "Financial Reporting"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Managed books for 15+ US small businesses. Handled full-cycle accounting including month-end close and quarterly tax filings.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "fin-002",
    name: "Vandana T.",
    role: "Accounts Payable Specialist",
    category: "finance-accounting",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Invoice Processing", "Bill.com", "Vendor Management", "Bank Reconciliation", "QuickBooks", "Expense Reports"],
    timezone: "EST / CST flexible",
    availability: "1-week",
    highlights: "Processed 800+ invoices/month for a US property management firm. Maintained vendor payment accuracy at 99.8% with zero late payments.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "fin-003",
    name: "Sanjay B.",
    role: "Financial Analyst",
    category: "finance-accounting",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["Financial Modeling", "Excel Advanced", "Budgeting", "Forecasting", "Power BI", "Variance Analysis"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Built financial models for 3 US startups during fundraising. Created investor-ready dashboards and 5-year revenue projections.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "fin-004",
    name: "Geeta K.",
    role: "Bookkeeper",
    category: "finance-accounting",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["QuickBooks Desktop", "Bank Reconciliation", "Data Entry", "Gusto", "Invoice Management", "Expense Categorization"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Specialized in QuickBooks for service-based businesses. Accurate reconciliation and payroll processing via Gusto for 10+ US clients.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "fin-005",
    name: "Mohan L.",
    role: "Tax Preparation Specialist",
    category: "finance-accounting",
    experience: "7 years",
    rate: "$9/hr",
    skills: ["Tax Returns", "IRS Compliance", "QuickBooks", "Lacerte", "Multi-State Filing", "1099 Processing"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Prepared 300+ US individual and business tax returns. Expert in multi-state filing and IRS correspondence resolution.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "fin-006",
    name: "Ankita D.",
    role: "Accounts Receivable Specialist",
    category: "finance-accounting",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Collections", "Invoicing", "Cash Application", "Aging Reports", "Xero", "Customer Communication"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Reduced DSO from 52 to 34 days for a US services company. Managed AR for portfolios exceeding $5M in outstanding receivables.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "fin-007",
    name: "Pankaj S.",
    role: "Payroll Specialist",
    category: "finance-accounting",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["ADP", "Gusto", "Payroll Tax", "Benefits Administration", "Compliance", "Multi-State Payroll"],
    timezone: "EST / CST flexible",
    availability: "2-weeks",
    highlights: "Processed biweekly payroll for 500+ employees across 12 US states. Expert in ADP Workforce Now and Gusto. Zero compliance violations.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "fin-008",
    name: "Neelam R.",
    role: "Staff Accountant",
    category: "finance-accounting",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["General Ledger", "Journal Entries", "Month-End Close", "GAAP", "QuickBooks Online", "Reconciliation"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Handled month-end close for 3 US companies simultaneously. Maintained GAAP-compliant financials and prepared audit-ready workpapers.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "fin-009",
    name: "Vivek H.",
    role: "Financial Controller",
    category: "finance-accounting",
    experience: "10 years",
    rate: "$10/hr",
    skills: ["Financial Statements", "Cash Flow Management", "Budgeting", "Audit Prep", "NetSuite", "Team Management"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Served as fractional controller for 2 US mid-market companies. Managed $20M+ annual budgets and led finance teams of 4-6 people.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "fin-010",
    name: "Komal J.",
    role: "Bookkeeper",
    category: "finance-accounting",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["Xero", "Wave", "Receipt Management", "Bank Feeds", "GST/Sales Tax", "Financial Reports"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Managed books for 12 Australian and US small businesses on Xero. Specialized in e-commerce accounting with Shopify integration.",
    aiTools: ["ChatGPT", "Dext AI"],
  },
  {
    id: "fin-011",
    name: "Ashwin P.",
    role: "Audit Associate",
    category: "finance-accounting",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Internal Audit", "SOX Compliance", "Risk Assessment", "Workpaper Prep", "Excel", "COSO Framework"],
    timezone: "EST / PST flexible",
    availability: "2-weeks",
    highlights: "Supported SOX compliance audits for 2 US publicly traded companies. Identified 15+ control deficiencies and recommended remediation steps.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "fin-012",
    name: "Shilpa M.",
    role: "Financial Analyst",
    category: "finance-accounting",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["FP&A", "Scenario Analysis", "Tableau", "SQL", "Excel Macros", "KPI Dashboards"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Built automated KPI dashboards in Tableau for a US retail chain. Delivered weekly variance analysis reports to VP Finance.",
    aiTools: ["ChatGPT", "Claude"],
  },

  /* ════════════════════════════════════════════════
     DIGITAL MARKETING (mkt-001 to mkt-012)
     ════════════════════════════════════════════════ */
  {
    id: "mkt-001",
    name: "Varun J.",
    role: "Senior Digital Marketer",
    category: "digital-marketing",
    experience: "7 years",
    rate: "$11/hr",
    skills: ["SEO", "Google Ads", "Facebook Ads", "Content Strategy", "Analytics", "Email Marketing"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Grew organic traffic 4x for a B2B SaaS company. Managed $50K+/month ad spend across Google and Meta with 3.2x average ROAS.",
    aiTools: ["ChatGPT", "Jasper", "Surfer SEO"],
  },
  {
    id: "mkt-002",
    name: "Shruti D.",
    role: "Social Media Manager",
    category: "digital-marketing",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["Instagram", "LinkedIn", "Content Creation", "Canva", "Hootsuite", "Community Management"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Managed social accounts for 8 brands across LinkedIn, Instagram, and TikTok. Grew a B2B LinkedIn page from 2K to 25K followers.",
    aiTools: ["ChatGPT", "Canva AI", "CapCut"],
  },
  {
    id: "mkt-003",
    name: "Akash B.",
    role: "PPC Specialist",
    category: "digital-marketing",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["Google Ads", "Bing Ads", "Landing Pages", "A/B Testing", "Conversion Tracking", "Google Analytics 4"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Managed $200K+ in annual ad spend for US e-commerce and lead gen clients. Reduced CPA by 45% through systematic landing page optimization.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "mkt-004",
    name: "Namita K.",
    role: "Email Marketing Specialist",
    category: "digital-marketing",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["Klaviyo", "Mailchimp", "ActiveCampaign", "Drip Campaigns", "Segmentation", "A/B Testing"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Built email flows generating $400K+ in attributed revenue for a US DTC brand. Expert in Klaviyo segmentation and lifecycle automation.",
    aiTools: ["ChatGPT", "Jasper"],
  },
  {
    id: "mkt-005",
    name: "Rohit T.",
    role: "Performance Marketing Manager",
    category: "digital-marketing",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["Meta Ads", "Google Ads", "TikTok Ads", "Attribution", "ROAS Optimization", "Creative Strategy"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Scaled a DTC brand from $50K to $300K/month in revenue through paid social. Expert in creative testing frameworks and attribution modeling.",
    aiTools: ["ChatGPT", "Claude", "Canva AI"],
  },
  {
    id: "mkt-006",
    name: "Aparna V.",
    role: "Content Marketing Specialist",
    category: "digital-marketing",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["Blog Strategy", "Thought Leadership", "Distribution", "HubSpot", "Content Calendar", "Repurposing"],
    timezone: "GMT / AEST flexible",
    availability: "1-week",
    highlights: "Developed content strategies for 4 US B2B companies. Increased MQL pipeline by 60% through gated content and SEO-driven blog programs.",
    aiTools: ["ChatGPT", "Jasper", "Surfer SEO"],
  },
  {
    id: "mkt-007",
    name: "Dhruv M.",
    role: "Marketing Automation Specialist",
    category: "digital-marketing",
    experience: "5 years",
    rate: "$10/hr",
    skills: ["HubSpot", "Marketo", "Pardot", "Lead Scoring", "Workflow Automation", "CRM Integration"],
    timezone: "EST / CST flexible",
    availability: "2-weeks",
    highlights: "Implemented HubSpot Marketing Hub for 3 US mid-market companies. Built lead scoring models that improved SQL conversion by 40%.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "mkt-008",
    name: "Tanvi R.",
    role: "Social Media Manager",
    category: "digital-marketing",
    experience: "3 years",
    rate: "$7/hr",
    skills: ["TikTok", "Instagram Reels", "Video Editing", "Trend Analysis", "Influencer Outreach", "Analytics"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Grew a US wellness brand's TikTok from 0 to 85K followers in 6 months. Created viral short-form content averaging 500K+ views per post.",
    aiTools: ["CapCut", "Canva AI", "ChatGPT"],
  },
  {
    id: "mkt-009",
    name: "Girish N.",
    role: "SEO Strategist",
    category: "digital-marketing",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["Technical SEO", "Ahrefs", "Semrush", "Link Building", "Local SEO", "Schema Markup"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Achieved 200+ first-page rankings for a US legal services firm. Expert in technical SEO audits and white-hat link building campaigns.",
    aiTools: ["Surfer SEO", "ChatGPT", "Clearscope"],
  },
  {
    id: "mkt-010",
    name: "Kavya L.",
    role: "PPC Specialist",
    category: "digital-marketing",
    experience: "3 years",
    rate: "$7/hr",
    skills: ["Google Ads", "Facebook Ads", "Keyword Research", "Ad Copywriting", "Bid Management", "Reporting"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Managed Google Ads campaigns for 10+ US local service businesses. Consistently achieved 4x+ ROAS with budgets ranging $2K-$15K/month.",
    aiTools: ["ChatGPT", "Jasper"],
  },
  {
    id: "mkt-011",
    name: "Siddharth G.",
    role: "Growth Marketing Manager",
    category: "digital-marketing",
    experience: "7 years",
    rate: "$11/hr",
    skills: ["Growth Hacking", "Product-Led Growth", "Analytics", "Experimentation", "Mixpanel", "Funnel Optimization"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Led growth experiments for a US fintech startup, increasing activation rate by 35%. Built experiment velocity from 2 to 12 tests/month.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "mkt-012",
    name: "Poornima H.",
    role: "Influencer Marketing Coordinator",
    category: "digital-marketing",
    experience: "3 years",
    rate: "$7/hr",
    skills: ["Influencer Outreach", "Campaign Management", "Contract Negotiation", "ROI Tracking", "Instagram", "YouTube"],
    timezone: "GMT / AEST flexible",
    availability: "2-weeks",
    highlights: "Managed influencer campaigns for 3 US DTC brands. Coordinated 100+ influencer partnerships generating $1.2M in tracked revenue.",
    aiTools: ["ChatGPT", "Canva AI"],
  },

  /* ════════════════════════════════════════════════
     LEGAL & COMPLIANCE (leg-001 to leg-012)
     ════════════════════════════════════════════════ */
  {
    id: "leg-001",
    name: "Nandini S.",
    role: "Senior Paralegal",
    category: "legal-compliance",
    experience: "7 years",
    rate: "$10/hr",
    skills: ["Legal Research", "Contract Review", "E-Discovery", "Clio", "Westlaw", "Corporate Compliance"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Supported 4 US law firms across corporate, real estate, and IP matters. Reviewed 500+ contracts and managed document production for litigation.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-002",
    name: "Abhishek R.",
    role: "Contract Analyst",
    category: "legal-compliance",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["Contract Drafting", "Redlining", "NDA Review", "MSA Review", "Risk Assessment", "Ironclad"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Reviewed and redlined 300+ commercial contracts for US tech companies. Specializes in SaaS agreements, NDAs, and vendor contracts.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-003",
    name: "Madhuri P.",
    role: "Compliance Analyst",
    category: "legal-compliance",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["GDPR", "CCPA", "SOC 2", "Policy Drafting", "Risk Assessment", "Compliance Monitoring"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Led GDPR and CCPA compliance programs for 3 US SaaS companies. Drafted privacy policies and conducted 20+ data protection impact assessments.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-004",
    name: "Deepika N.",
    role: "Legal Research Specialist",
    category: "legal-compliance",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["Case Law Research", "Westlaw", "LexisNexis", "Memorandum Drafting", "Statutory Analysis", "Citation Checking"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Prepared 200+ legal research memos for US litigation and corporate law practices. Expert in Westlaw and LexisNexis research techniques.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-005",
    name: "Kiran T.",
    role: "Immigration Paralegal",
    category: "legal-compliance",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["H-1B Petitions", "I-140", "PERM", "Case Management", "USCIS Filing", "Client Communication"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Processed 150+ H-1B and green card petitions for US immigration firms. Maintained 95% approval rate on first filing across all visa categories.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "leg-006",
    name: "Sunil M.",
    role: "Corporate Paralegal",
    category: "legal-compliance",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["Entity Formation", "Corporate Governance", "Board Resolutions", "SEC Filings", "Due Diligence", "Minute Books"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Handled corporate governance for 20+ US entities including LLCs, corporations, and partnerships. Managed annual compliance filings across 15 states.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-007",
    name: "Renu G.",
    role: "E-Discovery Specialist",
    category: "legal-compliance",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["Relativity", "Document Review", "TAR", "Data Processing", "Privilege Logging", "Production"],
    timezone: "EST / GMT flexible",
    availability: "2-weeks",
    highlights: "Managed e-discovery workflows for 3 Am Law 100 firms. Processed document collections exceeding 2TB and reviewed 500K+ documents.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "leg-008",
    name: "Anil K.",
    role: "Intellectual Property Paralegal",
    category: "legal-compliance",
    experience: "7 years",
    rate: "$11/hr",
    skills: ["Trademark Filing", "Patent Prosecution", "IP Portfolio Management", "USPTO", "Docketing", "IP Research"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Filed 200+ trademark applications and managed patent portfolios for US tech companies. Expert in USPTO procedures and IP docketing systems.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-009",
    name: "Lavanya B.",
    role: "Compliance Analyst",
    category: "legal-compliance",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["AML/KYC", "Regulatory Compliance", "Risk Monitoring", "Policy Review", "Audit Support", "Compliance Training"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Conducted AML/KYC reviews for a US fintech processing $100M+ in transactions. Developed compliance training materials for 200+ employees.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "leg-010",
    name: "Sagar V.",
    role: "Contract Administrator",
    category: "legal-compliance",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["Contract Lifecycle Management", "Agiloft", "Renewal Tracking", "Obligation Management", "Vendor Compliance", "Reporting"],
    timezone: "EST / CST flexible",
    availability: "1-week",
    highlights: "Administered 1,000+ active contracts for a US healthcare company. Built renewal tracking dashboards that prevented $2M in auto-renewal overspend.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "leg-011",
    name: "Hema D.",
    role: "Legal Secretary",
    category: "legal-compliance",
    experience: "8 years",
    rate: "$12/hr",
    skills: ["Court Filings", "Calendar Management", "Transcription", "Legal Formatting", "Client Billing", "Document Management"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Provided secretarial support to 6 attorneys at US law firms. Managed complex litigation calendars and filed 1,000+ court documents.",
    aiTools: ["ChatGPT", "Grammarly"],
  },
  {
    id: "leg-012",
    name: "Prashant J.",
    role: "Data Privacy Specialist",
    category: "legal-compliance",
    experience: "5 years",
    rate: "$10/hr",
    skills: ["GDPR", "CCPA", "Privacy Impact Assessment", "Data Mapping", "Vendor Risk", "OneTrust"],
    timezone: "GMT / AEST flexible",
    availability: "2-weeks",
    highlights: "Implemented OneTrust for 2 US enterprises. Conducted 30+ privacy impact assessments and built data flow inventories across 50+ systems.",
    aiTools: ["ChatGPT", "Claude"],
  },

  /* ════════════════════════════════════════════════
     HEALTHCARE & RCM (hc-001 to hc-012)
     ════════════════════════════════════════════════ */
  {
    id: "hc-001",
    name: "Usha K.",
    role: "Medical Coder (CPC Certified)",
    category: "healthcare-rcm",
    experience: "6 years",
    rate: "$9/hr",
    skills: ["ICD-10", "CPT Coding", "Denial Management", "Epic", "Claims Submission", "HIPAA"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "CPC certified. Maintained 97% clean claim rate across cardiology and internal medicine. Experienced with Epic and Athenahealth.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-002",
    name: "Ramesh G.",
    role: "Medical Billing Specialist",
    category: "healthcare-rcm",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Claim Submission", "Payment Posting", "AR Follow-up", "Kareo", "AdvancedMD", "Eligibility Verification"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Processed 500+ claims/week for a US multi-specialty group. Reduced claim denials by 30% through pre-submission audits.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-003",
    name: "Savita L.",
    role: "Denial Management Specialist",
    category: "healthcare-rcm",
    experience: "7 years",
    rate: "$10/hr",
    skills: ["Denial Analysis", "Appeals", "Root Cause Identification", "Payer Negotiations", "Reporting", "Epic"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Recovered $3.2M in denied claims over 2 years for a US hospital system. Expert in writing successful appeals for commercial and Medicare payers.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "hc-004",
    name: "Manoj B.",
    role: "Medical Coder (CCS Certified)",
    category: "healthcare-rcm",
    experience: "8 years",
    rate: "$10/hr",
    skills: ["Inpatient Coding", "DRG Assignment", "ICD-10-PCS", "Clinical Documentation", "Coding Audits", "3M Encoder"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "CCS certified inpatient coder with 98% accuracy rate. Coded for 3 US hospital systems across orthopedics, cardiology, and general surgery.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-005",
    name: "Prema S.",
    role: "Prior Authorization Specialist",
    category: "healthcare-rcm",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Prior Auth Requests", "Insurance Verification", "Clinical Documentation", "Payer Portals", "Follow-up", "EMR Systems"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Processed 100+ prior authorizations/week for a US specialty practice. Achieved 92% first-pass approval rate through thorough clinical documentation.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-006",
    name: "Dinesh R.",
    role: "Revenue Cycle Analyst",
    category: "healthcare-rcm",
    experience: "6 years",
    rate: "$9/hr",
    skills: ["RCM Analytics", "KPI Tracking", "Charge Capture", "Revenue Leakage", "Tableau", "Process Improvement"],
    timezone: "Any timezone",
    availability: "2-weeks",
    highlights: "Identified $1.5M in annual revenue leakage for a US healthcare group. Built RCM dashboards tracking 15+ KPIs across 8 practice locations.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "hc-007",
    name: "Anita M.",
    role: "Patient Account Representative",
    category: "healthcare-rcm",
    experience: "3 years",
    rate: "$7/hr",
    skills: ["Patient Billing", "Payment Plans", "Insurance Follow-up", "Statement Processing", "Collections", "Customer Service"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Managed patient accounts for a 200-bed US hospital. Improved patient collections by 25% through proactive payment plan setup and communication.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-008",
    name: "Vijay P.",
    role: "Credentialing Specialist",
    category: "healthcare-rcm",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Provider Enrollment", "CAQH", "PECOS", "License Verification", "Payer Credentialing", "Re-credentialing"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Credentialed 150+ providers across 30 US insurance panels. Average turnaround of 45 days with 98% first-submission acceptance rate.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-009",
    name: "Lata V.",
    role: "Medical Billing Specialist",
    category: "healthcare-rcm",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["CMS-1500", "UB-04", "ERA Processing", "Clearinghouse", "Claim Scrubbing", "Athenahealth"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Submitted 400+ clean claims/week with 96% first-pass rate. Expert in Athenahealth workflows for multi-specialty physician groups.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-010",
    name: "Santosh N.",
    role: "Charge Entry Specialist",
    category: "healthcare-rcm",
    experience: "3 years",
    rate: "$7/hr",
    skills: ["Charge Entry", "Superbill Processing", "CPT/ICD Verification", "EMR Navigation", "Data Accuracy", "Productivity"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Processed 250+ superbills/day with 99.2% accuracy for a US orthopedic practice. Reduced charge lag from 5 days to same-day entry.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "hc-011",
    name: "Kaveri D.",
    role: "Medical Coding Auditor",
    category: "healthcare-rcm",
    experience: "8 years",
    rate: "$10/hr",
    skills: ["Coding Audits", "Compliance Reviews", "Education", "Risk Adjustment", "HCC Coding", "Documentation Improvement"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Audited 5,000+ charts for US healthcare systems. Identified $800K in coding accuracy improvements and delivered coder education programs.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "hc-012",
    name: "Jayesh T.",
    role: "AR Follow-up Specialist",
    category: "healthcare-rcm",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Insurance Follow-up", "Aging Analysis", "Payer Calls", "Claim Status", "Escalation", "Reporting"],
    timezone: "EST / CST flexible",
    availability: "2-weeks",
    highlights: "Worked AR buckets totaling $8M for a US revenue cycle company. Reduced 90+ day AR by 40% through systematic follow-up and escalation.",
    aiTools: ["ChatGPT"],
  },

  /* ════════════════════════════════════════════════
     CUSTOMER SUPPORT (cs-001 to cs-012)
     ════════════════════════════════════════════════ */
  {
    id: "cs-001",
    name: "Prakash L.",
    role: "Customer Support Specialist",
    category: "customer-support",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["Zendesk", "Live Chat", "Phone Support", "Email Support", "Shopify", "Returns Processing"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Handled 80+ tickets/day for a US Shopify brand. CSAT score consistently above 95%. Proficient in Zendesk and Intercom.",
    aiTools: ["ChatGPT", "Zendesk AI"],
  },
  {
    id: "cs-002",
    name: "Anjali V.",
    role: "Technical Support Agent",
    category: "customer-support",
    experience: "5 years",
    rate: "$7/hr",
    skills: ["Troubleshooting", "SaaS Support", "Jira", "Freshdesk", "Screen Sharing", "Knowledge Base"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Provided Tier 2 technical support for a US SaaS company with 10K+ users. Resolved complex issues with 94% first-contact resolution rate.",
    aiTools: ["ChatGPT", "Zendesk AI"],
  },
  {
    id: "cs-003",
    name: "Manoj V.",
    role: "Chat Support Specialist",
    category: "customer-support",
    experience: "3 years",
    rate: "$5/hr",
    skills: ["Intercom", "Live Chat", "Canned Responses", "Multitasking", "Product Knowledge", "Upselling"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Managed 4 simultaneous chat conversations with an average response time of 30 seconds. Achieved 92% customer satisfaction across 15K+ chats.",
    aiTools: ["ChatGPT", "Zendesk AI"],
  },
  {
    id: "cs-004",
    name: "Savitha K.",
    role: "Customer Success Associate",
    category: "customer-support",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["Onboarding", "Account Management", "Churn Prevention", "HubSpot", "Health Scoring", "Renewal Calls"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Managed onboarding for 200+ accounts at a US SaaS company. Reduced churn by 20% through proactive health monitoring and quarterly business reviews.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "cs-005",
    name: "Imran H.",
    role: "Phone Support Agent",
    category: "customer-support",
    experience: "5 years",
    rate: "$6/hr",
    skills: ["Inbound Calls", "Outbound Calls", "CRM", "Conflict Resolution", "Call Scripts", "Quality Assurance"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Handled 60+ inbound calls/day for a US insurance company. Maintained quality scores above 90% and average handle time under 6 minutes.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "cs-006",
    name: "Bhavya R.",
    role: "Help Desk Specialist",
    category: "customer-support",
    experience: "3 years",
    rate: "$5/hr",
    skills: ["Ticketing Systems", "IT Support", "Password Resets", "Remote Desktop", "Documentation", "ServiceNow"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Resolved 100+ IT help desk tickets/week for a US managed services provider. Created 50+ knowledge base articles reducing repeat tickets by 30%.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "cs-007",
    name: "Neeraj S.",
    role: "E-commerce Support Agent",
    category: "customer-support",
    experience: "3 years",
    rate: "$5/hr",
    skills: ["Shopify", "Amazon Support", "Order Tracking", "Refund Processing", "Product Inquiries", "Gorgias"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Provided support for 3 US e-commerce brands on Shopify and Amazon. Processed 500+ refunds/exchanges monthly while maintaining 4.9-star ratings.",
    aiTools: ["ChatGPT", "Zendesk AI"],
  },
  {
    id: "cs-008",
    name: "Rashmi B.",
    role: "Customer Support Team Lead",
    category: "customer-support",
    experience: "6 years",
    rate: "$7/hr",
    skills: ["Team Management", "Quality Monitoring", "Escalation Handling", "Training", "SLA Tracking", "Zendesk Admin"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Led a 10-person support team for a US software company. Improved team CSAT from 87% to 96% and reduced average resolution time by 35%.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "cs-009",
    name: "Vivek D.",
    role: "Technical Support Agent",
    category: "customer-support",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["API Troubleshooting", "Log Analysis", "Bug Reporting", "Confluence", "Slack", "Customer Communication"],
    timezone: "Any timezone",
    availability: "2-weeks",
    highlights: "Provided API-level support for a US developer tools company. Resolved integration issues for enterprise customers generating $5M+ ARR.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "cs-010",
    name: "Parveen J.",
    role: "Bilingual Support Agent",
    category: "customer-support",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["English/Hindi", "Multilingual Support", "Zendesk", "Phone", "Email", "Cultural Sensitivity"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Provided bilingual customer support for a US telecom company. Handled 70+ interactions/day across phone, email, and chat channels.",
    aiTools: ["ChatGPT", "Grammarly"],
  },
  {
    id: "cs-011",
    name: "Suman P.",
    role: "Chat Support Specialist",
    category: "customer-support",
    experience: "2 years",
    rate: "$5/hr",
    skills: ["Drift", "Intercom", "Pre-sales Chat", "Lead Qualification", "FAQ Handling", "Typing Speed 80WPM"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Qualified 50+ leads/week through live chat for a US B2B SaaS company. Converted 18% of chat interactions into booked demos.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "cs-012",
    name: "Kirti M.",
    role: "Customer Support Specialist",
    category: "customer-support",
    experience: "4 years",
    rate: "$6/hr",
    skills: ["Freshdesk", "Email Support", "Social Media Support", "Complaint Resolution", "SOP Creation", "Reporting"],
    timezone: "GMT / AEST flexible",
    availability: "1-week",
    highlights: "Managed multi-channel support for a US subscription box company. Handled 1,000+ tickets/month across email, social, and phone with 97% CSAT.",
    aiTools: ["ChatGPT", "Zendesk AI"],
  },

  /* ════════════════════════════════════════════════
     CYBERSECURITY & IT (sec-001 to sec-012)
     ════════════════════════════════════════════════ */
  {
    id: "sec-001",
    name: "Ajay N.",
    role: "Security Analyst",
    category: "cybersecurity",
    experience: "5 years",
    rate: "$11/hr",
    skills: ["SIEM", "Incident Response", "Threat Hunting", "Splunk", "Firewalls", "Vulnerability Management"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Monitored SOC operations for a US MSP serving 50+ clients. Investigated 200+ security incidents and reduced mean time to detect by 40%.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "sec-002",
    name: "Pallav S.",
    role: "Penetration Tester",
    category: "cybersecurity",
    experience: "6 years",
    rate: "$13/hr",
    skills: ["Burp Suite", "Nmap", "Metasploit", "Web App Testing", "Network Pentesting", "OWASP Top 10"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "CEH and OSCP certified. Conducted 100+ penetration tests for US companies across fintech, healthcare, and e-commerce sectors.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "sec-003",
    name: "Rukmini T.",
    role: "GRC Analyst",
    category: "cybersecurity",
    experience: "5 years",
    rate: "$10/hr",
    skills: ["SOC 2", "ISO 27001", "Risk Assessment", "Policy Writing", "Vendor Risk", "Compliance Audits"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Led SOC 2 Type II compliance programs for 4 US SaaS companies. Authored 50+ security policies and conducted vendor risk assessments.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "sec-004",
    name: "Gauresh M.",
    role: "Cloud Security Engineer",
    category: "cybersecurity",
    experience: "6 years",
    rate: "$12/hr",
    skills: ["AWS Security", "Azure Security", "IAM", "CloudTrail", "GuardDuty", "Infrastructure as Code"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Secured AWS environments for 3 US fintech companies. Implemented zero-trust architecture and reduced security findings by 70% in audits.",
    aiTools: ["GitHub Copilot", "ChatGPT"],
  },
  {
    id: "sec-005",
    name: "Snehal V.",
    role: "SOC Analyst",
    category: "cybersecurity",
    experience: "3 years",
    rate: "$9/hr",
    skills: ["SIEM Monitoring", "Alert Triage", "Log Analysis", "CrowdStrike", "Phishing Investigation", "Incident Triage"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Triaged 100+ daily alerts in a 24/7 US SOC environment. Identified and escalated 15 critical threats before they caused damage.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "sec-006",
    name: "Hemant K.",
    role: "Network Security Engineer",
    category: "cybersecurity",
    experience: "7 years",
    rate: "$12/hr",
    skills: ["Firewall Configuration", "VPN", "IDS/IPS", "Cisco", "Palo Alto", "Network Segmentation"],
    timezone: "EST / GMT flexible",
    availability: "2-weeks",
    highlights: "Designed and managed network security for a US healthcare system with 15 locations. Implemented network segmentation reducing attack surface by 60%.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "sec-007",
    name: "Radhika J.",
    role: "Application Security Engineer",
    category: "cybersecurity",
    experience: "5 years",
    rate: "$11/hr",
    skills: ["SAST/DAST", "Code Review", "DevSecOps", "OWASP", "SonarQube", "Secure SDLC"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Integrated security into CI/CD pipelines for 3 US dev teams. Reduced critical vulnerabilities by 80% through automated SAST/DAST scanning.",
    aiTools: ["GitHub Copilot", "ChatGPT", "Claude"],
  },
  {
    id: "sec-008",
    name: "Tushar P.",
    role: "Identity & Access Management Specialist",
    category: "cybersecurity",
    experience: "5 years",
    rate: "$10/hr",
    skills: ["Okta", "Azure AD", "SSO", "MFA", "RBAC", "Privileged Access Management"],
    timezone: "GMT / AEST flexible",
    availability: "immediate",
    highlights: "Implemented Okta SSO and MFA for a US enterprise with 5,000+ users. Designed RBAC policies reducing excessive permissions by 50%.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "sec-009",
    name: "Jaya R.",
    role: "Security Analyst",
    category: "cybersecurity",
    experience: "4 years",
    rate: "$10/hr",
    skills: ["Vulnerability Scanning", "Nessus", "Qualys", "Patch Management", "Risk Reporting", "Security Awareness"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Managed vulnerability management program for a US financial services firm. Scanned 2,000+ assets monthly and drove 95% patch compliance.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "sec-010",
    name: "Mayur D.",
    role: "Cybersecurity Consultant",
    category: "cybersecurity",
    experience: "8 years",
    rate: "$14/hr",
    skills: ["Security Architecture", "Incident Response Planning", "NIST Framework", "CIS Controls", "Board Reporting", "Strategy"],
    timezone: "EST / PST flexible",
    availability: "1-week",
    highlights: "Advised 10+ US mid-market companies on cybersecurity strategy. Built incident response plans and conducted tabletop exercises for C-suite teams.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "sec-011",
    name: "Sonia G.",
    role: "GRC Analyst",
    category: "cybersecurity",
    experience: "4 years",
    rate: "$10/hr",
    skills: ["HIPAA", "PCI DSS", "Risk Register", "Control Testing", "Audit Prep", "ServiceNow GRC"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Managed HIPAA and PCI DSS compliance for a US healthcare SaaS company. Prepared for and passed 3 consecutive external audits with zero findings.",
    aiTools: ["ChatGPT"],
  },
  {
    id: "sec-012",
    name: "Bhushan L.",
    role: "Incident Response Analyst",
    category: "cybersecurity",
    experience: "5 years",
    rate: "$11/hr",
    skills: ["Digital Forensics", "Malware Analysis", "Incident Handling", "YARA Rules", "Threat Intelligence", "Containment"],
    timezone: "EST / GMT flexible",
    availability: "2-weeks",
    highlights: "Responded to 50+ security incidents including ransomware and BEC attacks for US companies. Reduced average containment time from 48 to 8 hours.",
    aiTools: ["ChatGPT", "Claude"],
  },

  /* ════════════════════════════════════════════════
     GRAPHIC DESIGN (des-001 to des-012)
     ════════════════════════════════════════════════ */
  {
    id: "des-001",
    name: "Neha G.",
    role: "Senior Graphic Designer",
    category: "design",
    experience: "6 years",
    rate: "$9/hr",
    skills: ["Figma", "Photoshop", "Illustrator", "Brand Identity", "Social Media Graphics", "Print Design"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Created brand identities for 8 US startups. Specializes in cohesive visual systems spanning digital, social, and print collateral.",
    aiTools: ["Midjourney", "Canva AI", "Adobe Firefly"],
  },
  {
    id: "des-002",
    name: "Vishal T.",
    role: "UI/UX Designer",
    category: "design",
    experience: "5 years",
    rate: "$9/hr",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Designed UI for 6 US SaaS products. Built a component library used across 3 product teams, reducing design-to-dev handoff time by 50%.",
    aiTools: ["Midjourney", "ChatGPT", "Adobe Firefly"],
  },
  {
    id: "des-003",
    name: "Aarti K.",
    role: "Motion Graphics Designer",
    category: "design",
    experience: "4 years",
    rate: "$8/hr",
    skills: ["After Effects", "Premiere Pro", "Lottie Animations", "Explainer Videos", "Social Media Video", "Storyboarding"],
    timezone: "GMT / AEST flexible",
    availability: "1-week",
    highlights: "Produced 100+ motion graphics and explainer videos for US brands. Created animated product demos that increased landing page conversion by 25%.",
    aiTools: ["Adobe Firefly", "CapCut", "ChatGPT"],
  },
  {
    id: "des-004",
    name: "Kunal M.",
    role: "Brand Designer",
    category: "design",
    experience: "7 years",
    rate: "$10/hr",
    skills: ["Logo Design", "Brand Guidelines", "Typography", "Color Theory", "Illustrator", "InDesign"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Developed comprehensive brand identities for 12 US companies including logos, style guides, and brand books. Expert in typography-driven design.",
    aiTools: ["Midjourney", "Adobe Firefly", "Canva AI"],
  },
  {
    id: "des-005",
    name: "Roshni P.",
    role: "Web Designer",
    category: "design",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Figma", "Webflow", "Responsive Design", "Landing Pages", "WordPress", "CSS"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Designed and built 30+ marketing websites on Webflow for US businesses. Average page load time under 2 seconds with mobile-first approach.",
    aiTools: ["Canva AI", "ChatGPT"],
  },
  {
    id: "des-006",
    name: "Omkar S.",
    role: "Presentation Designer",
    category: "design",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["PowerPoint", "Google Slides", "Pitch Decks", "Data Visualization", "Infographics", "Template Design"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Designed 80+ investor pitch decks for US startups. Created presentation templates adopted company-wide by 3 enterprise clients.",
    aiTools: ["Canva AI", "ChatGPT", "Midjourney"],
  },
  {
    id: "des-007",
    name: "Priti J.",
    role: "UI Designer",
    category: "design",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Figma", "Sketch", "Material Design", "iOS HIG", "Component Libraries", "Responsive UI"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Designed mobile and web UIs for 5 US product companies. Built Figma design systems with 200+ reusable components and auto-layout.",
    aiTools: ["Midjourney", "ChatGPT"],
  },
  {
    id: "des-008",
    name: "Aryan B.",
    role: "Graphic Designer",
    category: "design",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["Canva", "Photoshop", "Social Media Graphics", "Email Templates", "Banner Ads", "Flyer Design"],
    timezone: "GMT / AEST flexible",
    availability: "2-weeks",
    highlights: "Created 1,500+ social media graphics for US e-commerce and lifestyle brands. Maintained consistent brand aesthetics across 5+ platforms.",
    aiTools: ["Canva AI", "Midjourney", "ChatGPT"],
  },
  {
    id: "des-009",
    name: "Mitali D.",
    role: "UX Researcher & Designer",
    category: "design",
    experience: "6 years",
    rate: "$10/hr",
    skills: ["User Interviews", "Personas", "Journey Mapping", "A/B Testing", "Figma", "Hotjar"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Conducted 100+ user interviews for US product teams. Research-driven redesign of a fintech app increased task completion rate by 40%.",
    aiTools: ["ChatGPT", "Claude", "Midjourney"],
  },
  {
    id: "des-010",
    name: "Govind R.",
    role: "Illustration Artist",
    category: "design",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Digital Illustration", "Procreate", "Illustrator", "Character Design", "Editorial Illustration", "Icon Design"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Created custom illustration sets for 10 US tech companies. Designed icon libraries with 500+ icons used across web and mobile products.",
    aiTools: ["Midjourney", "Adobe Firefly"],
  },
  {
    id: "des-011",
    name: "Sweta N.",
    role: "Packaging Designer",
    category: "design",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Packaging Design", "Illustrator", "InDesign", "3D Mockups", "Print Production", "Dieline Creation"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Designed packaging for 15 US consumer brands including food, beauty, and supplements. Created shelf-ready designs that boosted retail visibility.",
    aiTools: ["Adobe Firefly", "Midjourney", "ChatGPT"],
  },
  {
    id: "des-012",
    name: "Harsh V.",
    role: "Video Editor",
    category: "design",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Premiere Pro", "DaVinci Resolve", "Color Grading", "YouTube Editing", "Podcast Video", "Thumbnails"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Edited 400+ YouTube videos for US creators and brands. Specialized in fast-paced editing styles that increased average watch time by 35%.",
    aiTools: ["CapCut", "Adobe Firefly", "ChatGPT"],
  },

  /* ════════════════════════════════════════════════
     CONTENT & SEO (seo-001 to seo-012)
     ════════════════════════════════════════════════ */
  {
    id: "seo-001",
    name: "Manav B.",
    role: "SEO Specialist",
    category: "content-seo",
    experience: "6 years",
    rate: "$9/hr",
    skills: ["Technical SEO", "Ahrefs", "Surfer SEO", "Link Building", "Content Strategy", "Google Analytics 4"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Grew organic traffic from 5K to 80K/month for a US SaaS client. Expert in technical audits, content clusters, and white-hat link building.",
    aiTools: ["ChatGPT", "Surfer SEO", "Clearscope"],
  },
  {
    id: "seo-002",
    name: "Trupti K.",
    role: "SEO Content Writer",
    category: "content-seo",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["SEO Blogs", "Landing Pages", "Case Studies", "Email Copy", "WordPress", "Surfer SEO"],
    timezone: "Any timezone",
    availability: "immediate",
    highlights: "Produced 200+ SEO articles across B2B SaaS, fintech, and healthcare. Average 1,800-word articles ranking in top 10 within 3 months.",
    aiTools: ["ChatGPT", "Jasper", "Grammarly"],
  },
  {
    id: "seo-003",
    name: "Nilesh R.",
    role: "Link Building Specialist",
    category: "content-seo",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Outreach", "Guest Posting", "HARO", "Digital PR", "Ahrefs", "Relationship Building"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Built 500+ high-quality backlinks for US companies with average DR 50+. Expert in journalist outreach and digital PR campaigns.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "seo-004",
    name: "Sonali G.",
    role: "Content Strategist",
    category: "content-seo",
    experience: "6 years",
    rate: "$9/hr",
    skills: ["Content Planning", "Topic Clusters", "Keyword Research", "Editorial Calendars", "Content Audits", "Semrush"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Developed content strategies for 5 US B2B companies. Built topic cluster models that increased organic traffic by 150% in 8 months.",
    aiTools: ["ChatGPT", "Clearscope", "Surfer SEO"],
  },
  {
    id: "seo-005",
    name: "Rajat M.",
    role: "Technical SEO Specialist",
    category: "content-seo",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Site Audits", "Core Web Vitals", "Schema Markup", "Crawl Optimization", "Screaming Frog", "Google Search Console"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Resolved technical SEO issues for 20+ US websites. Improved Core Web Vitals scores from red to green, resulting in 30% organic traffic increase.",
    aiTools: ["ChatGPT", "Screaming Frog"],
  },
  {
    id: "seo-006",
    name: "Yamini S.",
    role: "Copywriter",
    category: "content-seo",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Sales Pages", "Ad Copy", "Email Sequences", "Brand Voice", "A/B Testing", "Conversion Optimization"],
    timezone: "GMT / AEST flexible",
    availability: "1-week",
    highlights: "Wrote conversion-focused copy for 10 US DTC brands. Sales page rewrites increased conversion rates by 35% on average across 8 campaigns.",
    aiTools: ["Jasper", "ChatGPT", "Grammarly"],
  },
  {
    id: "seo-007",
    name: "Pranav H.",
    role: "SEO Analyst",
    category: "content-seo",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["Google Analytics 4", "Search Console", "Keyword Tracking", "Competitor Analysis", "Reporting", "Data Studio"],
    timezone: "EST / CST flexible",
    availability: "immediate",
    highlights: "Built automated SEO reporting dashboards in Looker Studio for 8 US clients. Tracked 5,000+ keywords and delivered actionable monthly insights.",
    aiTools: ["ChatGPT", "Surfer SEO"],
  },
  {
    id: "seo-008",
    name: "Rina D.",
    role: "Content Writer",
    category: "content-seo",
    experience: "3 years",
    rate: "$6/hr",
    skills: ["Blog Writing", "Whitepapers", "E-books", "Research", "WordPress", "AP Style"],
    timezone: "Any timezone",
    availability: "2-weeks",
    highlights: "Authored 150+ long-form articles and 10 whitepapers for US technology companies. Expert in turning complex topics into accessible, engaging content.",
    aiTools: ["ChatGPT", "Grammarly", "Jasper"],
  },
  {
    id: "seo-009",
    name: "Deepesh T.",
    role: "Local SEO Specialist",
    category: "content-seo",
    experience: "4 years",
    rate: "$7/hr",
    skills: ["Google Business Profile", "Citation Building", "Local Link Building", "Review Management", "BrightLocal", "Whitespark"],
    timezone: "EST / PST flexible",
    availability: "immediate",
    highlights: "Managed local SEO for 30+ US service businesses. Achieved Google Map Pack rankings for 85% of target keywords within 4 months.",
    aiTools: ["ChatGPT", "Claude"],
  },
  {
    id: "seo-010",
    name: "Karuna V.",
    role: "SEO Content Writer",
    category: "content-seo",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Pillar Pages", "Comparison Articles", "Product Reviews", "BOFU Content", "Surfer SEO", "Internal Linking"],
    timezone: "EST / GMT flexible",
    availability: "1-week",
    highlights: "Specialized in high-intent commercial content. Wrote 100+ comparison and BOFU articles that generated $2M+ in attributed pipeline for US SaaS clients.",
    aiTools: ["Surfer SEO", "ChatGPT", "Clearscope"],
  },
  {
    id: "seo-011",
    name: "Abhinav N.",
    role: "Content Editor",
    category: "content-seo",
    experience: "7 years",
    rate: "$9/hr",
    skills: ["Editorial Management", "Style Guides", "Fact-Checking", "SEO Editing", "Team Training", "CMS Management"],
    timezone: "EST / GMT flexible",
    availability: "immediate",
    highlights: "Managed editorial operations for a US content agency producing 100+ articles/month. Trained 15 writers on SEO best practices and brand voice.",
    aiTools: ["Grammarly", "ChatGPT", "Claude"],
  },
  {
    id: "seo-012",
    name: "Trisha P.",
    role: "Content Strategist",
    category: "content-seo",
    experience: "5 years",
    rate: "$8/hr",
    skills: ["Content Gap Analysis", "Funnel Mapping", "Repurposing", "Distribution", "Analytics", "Notion"],
    timezone: "GMT / AEST flexible",
    availability: "2-weeks",
    highlights: "Built full-funnel content engines for 3 US startups. Repurposing framework turned 1 blog post into 12 distribution assets across 6 channels.",
    aiTools: ["ChatGPT", "Notion AI", "Clearscope"],
  },
];

/* ─── Weekly rotation system ─── */

/**
 * Active candidates for the current week.
 * Uses ISO week number to rotate through 4 batches of 30.
 * Each batch has 3 candidates per category for even distribution.
 */
function getWeekNumber(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 1);
  const diff = now.getTime() - start.getTime();
  const oneWeek = 604800000;
  return Math.floor(diff / oneWeek);
}

export const candidates: Candidate[] = (() => {
  const week = getWeekNumber();
  const batch = week % 4; // 4 batches of 30

  // Group by category, take 3 per category per batch
  const grouped = new Map<CandidateCategory, Candidate[]>();
  for (const c of allCandidates) {
    const arr = grouped.get(c.category) || [];
    arr.push(c);
    grouped.set(c.category, arr);
  }

  const result: Candidate[] = [];
  for (const [, arr] of grouped) {
    const start = batch * 3;
    result.push(...arr.slice(start, start + 3));
  }

  return result;
})();

/* ─── Helpers ─── */

export function getCandidatesByCategory(
  category?: CandidateCategory
): Candidate[] {
  if (!category) return candidates;
  return candidates.filter((c) => c.category === category);
}

export function searchCandidates(query: string): Candidate[] {
  const q = query.toLowerCase();
  return candidates.filter(
    (c) =>
      c.role.toLowerCase().includes(q) ||
      c.skills.some((s) => s.toLowerCase().includes(q)) ||
      c.highlights.toLowerCase().includes(q)
  );
}
