import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ["image/avif", "image/webp"],
  },

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "X-Frame-Options",
            value: "SAMEORIGIN",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
        ],
      },
      {
        // Cache static assets aggressively
        source: "/images/(.*)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
    ];
  },

  async redirects() {
    return [
      /* ─── WordPress infrastructure ─── */
      { source: "/wp-admin", destination: "/", permanent: true },
      { source: "/wp-admin{/:path}+", destination: "/", permanent: true },
      { source: "/wp-login.php", destination: "/", permanent: true },
      { source: "/wp-content{/:path}+", destination: "/", permanent: true },
      { source: "/wp-includes{/:path}+", destination: "/", permanent: true },
      { source: "/wp-json{/:path}+", destination: "/", permanent: true },
      { source: "/xmlrpc.php", destination: "/", permanent: true },
      { source: "/feed", destination: "/blog", permanent: true },
      { source: "/feed{/:path}+", destination: "/blog", permanent: true },

      /* ─── Catch-all: /hire/* → /services/* (structural URL change) ─── */
      { source: "/hire/:slug", destination: "/services/:slug", permanent: true },
      { source: "/hire/:slug/", destination: "/services/:slug", permanent: true },

      /* ─── Old hire pages → new /services/ routes (301) ─── */
      { source: "/hire-full-stack-developer", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-full-stack-developer/", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-digital-marketer", destination: "/services/digital-marketer", permanent: true },
      { source: "/hire-digital-marketer/", destination: "/services/digital-marketer", permanent: true },
      { source: "/hire-devops-engineers", destination: "/services/devops-engineers", permanent: true },
      { source: "/hire-devops-engineers/", destination: "/services/devops-engineers", permanent: true },
      { source: "/hire-cyber-security-expert", destination: "/services/cyber-security-expert", permanent: true },
      { source: "/hire-cyber-security-expert/", destination: "/services/cyber-security-expert", permanent: true },
      { source: "/hire-virtual-assistants", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-virtual-assistants/", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-virtual-assistant-for-bookkeeping", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/hire-virtual-assistant-for-bookkeeping/", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/hire-virtual-legal-staff", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/hire-virtual-legal-staff/", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/hire-revenue-cycle-management-staff", destination: "/services/revenue-cycle-management-staff", permanent: true },
      { source: "/hire-revenue-cycle-management-staff/", destination: "/services/revenue-cycle-management-staff", permanent: true },
      { source: "/hire-remote-employees-for-your-business", destination: "/services/remote-employees-for-your-business", permanent: true },
      { source: "/hire-remote-employees-for-your-business/", destination: "/services/remote-employees-for-your-business", permanent: true },
      /* Old hire pages that map to closest new pages */
      { source: "/hire-frontend-developer", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-frontend-developer/", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-remote-back-end-developer", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-remote-back-end-developer/", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-flutter-developer", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-flutter-developer/", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-remote-it-experts", destination: "/services/cyber-security-expert", permanent: true },
      { source: "/hire-remote-it-experts/", destination: "/services/cyber-security-expert", permanent: true },
      { source: "/hire-ai-virtual-assistants", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-ai-virtual-assistants/", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-remote-probate-specialists", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/hire-remote-probate-specialists/", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/hire-rag-developers", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-rag-developers/", destination: "/services/full-stack-developer", permanent: true },
      { source: "/hire-remote-ai-prompt-engineers", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-remote-ai-prompt-engineers/", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-remote-ai-prompt-engineers-2026", destination: "/services/virtual-assistants", permanent: true },
      { source: "/hire-remote-ai-prompt-engineers-2026/", destination: "/services/virtual-assistants", permanent: true },

      /* ─── Old service category pages → new /hire/ or /services ─── */
      { source: "/remote-staffing-services", destination: "/services", permanent: true },
      { source: "/remote-staffing-services/", destination: "/services", permanent: true },
      { source: "/remote-staffing-services/hire-remote-it-staff", destination: "/services/hire-remote-it-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-it-staff/", destination: "/services/hire-remote-it-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-finance-and-accounting-staff", destination: "/services/hire-remote-finance-accounting-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-finance-and-accounting-staff/", destination: "/services/hire-remote-finance-accounting-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-digital-marketing-staff", destination: "/services/hire-remote-digital-marketing-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-digital-marketing-staff/", destination: "/services/hire-remote-digital-marketing-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-legal-staff", destination: "/services/hire-remote-legal-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-legal-staff/", destination: "/services/hire-remote-legal-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-medical-staff", destination: "/services/hire-remote-medical-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-medical-staff/", destination: "/services/hire-remote-medical-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-administrative-and-assistant", destination: "/services/hire-remote-administrative-and-assistant", permanent: true },
      { source: "/remote-staffing-services/hire-remote-administrative-and-assistant/", destination: "/services/hire-remote-administrative-and-assistant", permanent: true },
      { source: "/remote-staffing-services/hire-remote-customer-support", destination: "/services/hire-remote-customer-support", permanent: true },
      { source: "/remote-staffing-services/hire-remote-customer-support/", destination: "/services/hire-remote-customer-support", permanent: true },
      { source: "/remote-staffing-services/hire-remote-designers", destination: "/services/hire-remote-designers", permanent: true },
      { source: "/remote-staffing-services/hire-remote-designers/", destination: "/services/hire-remote-designers", permanent: true },
      { source: "/remote-staffing-services/hire-remote-hr-and-recruitment-staff", destination: "/services/hire-remote-hr-and-recruitment-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-hr-and-recruitment-staff/", destination: "/services/hire-remote-hr-and-recruitment-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-research-analytics-staff", destination: "/services/hire-remote-research-analytics-staff", permanent: true },
      { source: "/remote-staffing-services/hire-remote-research-analytics-staff/", destination: "/services/hire-remote-research-analytics-staff", permanent: true },
      { source: "/remote-staffing-services/quality-assurance-and-testing", destination: "/services/quality-assurance-and-testing", permanent: true },
      { source: "/remote-staffing-services/quality-assurance-and-testing/", destination: "/services/quality-assurance-and-testing", permanent: true },
      { source: "/remote-staffing-services/sales-and-business-development", destination: "/services/sales-and-business-development", permanent: true },
      { source: "/remote-staffing-services/sales-and-business-development/", destination: "/services/sales-and-business-development", permanent: true },
      { source: "/remote-staffing-services/architecture-and-engineering", destination: "/services/architecture-engineering", permanent: true },
      { source: "/remote-staffing-services/architecture-and-engineering/", destination: "/services/architecture-engineering", permanent: true },

      /* ─── Track 2 articles (new blog URLs) ─── */
      { source: "/outsourcing-costs", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/outsourcing-costs/", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/hire-remote-developers-guide", destination: "/blog/hire-remote-developers-guide", permanent: true },
      { source: "/hire-remote-developers-guide/", destination: "/blog/hire-remote-developers-guide", permanent: true },
      { source: "/virtual-assistant-pricing", destination: "/blog/virtual-assistant-pricing", permanent: true },
      { source: "/virtual-assistant-pricing/", destination: "/blog/virtual-assistant-pricing", permanent: true },
      { source: "/ai-vs-outsourcing", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/ai-vs-outsourcing/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/outsource-payroll-services", destination: "/blog/outsource-payroll-services", permanent: true },
      { source: "/outsource-payroll-services/", destination: "/blog/outsource-payroll-services", permanent: true },
      { source: "/bpo-services", destination: "/blog/bpo-services", permanent: true },
      { source: "/bpo-services/", destination: "/blog/bpo-services", permanent: true },
      { source: "/best-remote-staffing-agencies", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/best-remote-staffing-agencies/", destination: "/blog/best-remote-staffing-agencies", permanent: true },

      /* ─── Old blog posts → best-match articles (301 permanent) ─── */
      { source: "/best-practices-for-hiring-remote-staff", destination: "/blog/best-practices-hiring-remote-staff", permanent: true },
      { source: "/best-practices-for-hiring-remote-staff/", destination: "/blog/best-practices-hiring-remote-staff", permanent: true },
      { source: "/complete-guide-to-remote-team-management", destination: "/blog/remote-team-management-guide", permanent: true },
      { source: "/complete-guide-to-remote-team-management/", destination: "/blog/remote-team-management-guide", permanent: true },
      { source: "/remote-staffing-guide", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-guide/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/staff-augmentation-services", destination: "/blog/staff-augmentation-services", permanent: true },
      { source: "/staff-augmentation-services/", destination: "/blog/staff-augmentation-services", permanent: true },
      { source: "/staff-augmentation-vs-outsourcing-vs-ai-which-model-in-2026", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/staff-augmentation-vs-outsourcing-vs-ai-which-model-in-2026/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/offshore-vs-outsourcing", destination: "/blog/offshore-vs-outsourcing", permanent: true },
      { source: "/offshore-vs-outsourcing/", destination: "/blog/offshore-vs-outsourcing", permanent: true },
      { source: "/why-remote-hiring", destination: "/blog/hire-remote-developers-guide", permanent: true },
      { source: "/why-remote-hiring/", destination: "/blog/hire-remote-developers-guide", permanent: true },
      { source: "/remote-vs-on-site-work-which-is-more-effective", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/remote-vs-on-site-work-which-is-more-effective/", destination: "/blog/ai-vs-outsourcing", permanent: true },

      /* ─── Old static pages → new equivalents ─── */
      { source: "/get-a-5-day-free-trial", destination: "/get-started", permanent: true },
      { source: "/get-a-5-day-free-trial/", destination: "/get-started", permanent: true },
      { source: "/certifications", destination: "/about", permanent: true },
      { source: "/certifications/", destination: "/about", permanent: true },
      { source: "/our-commitments", destination: "/about", permanent: true },
      { source: "/our-commitments/", destination: "/about", permanent: true },
      { source: "/our-people", destination: "/about", permanent: true },
      { source: "/our-people/", destination: "/about", permanent: true },
      { source: "/our-people{/:path}+", destination: "/about", permanent: true },
      { source: "/offices", destination: "/about", permanent: true },
      { source: "/offices/", destination: "/about", permanent: true },
      { source: "/ai-program", destination: "/about", permanent: true },
      { source: "/ai-program/", destination: "/about", permanent: true },
      { source: "/insights", destination: "/blog", permanent: true },
      { source: "/insights/", destination: "/blog", permanent: true },
      { source: "/remote-staffing-comparison", destination: "/services", permanent: true },
      { source: "/remote-staffing-comparison/", destination: "/services", permanent: true },
      { source: "/remote-staffing-cost", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/remote-staffing-cost/", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/remote-staffing-faqs", destination: "/about", permanent: true },
      { source: "/remote-staffing-faqs/", destination: "/about", permanent: true },
      { source: "/terms-of-use", destination: "/terms", permanent: true },
      { source: "/terms-of-use/", destination: "/terms", permanent: true },
      { source: "/cookie-policy", destination: "/privacy-policy", permanent: true },
      { source: "/cookie-policy/", destination: "/privacy-policy", permanent: true },
      { source: "/payment-terms", destination: "/terms", permanent: true },
      { source: "/payment-terms/", destination: "/terms", permanent: true },
      { source: "/gdpr-compliance-for-remote-hiring", destination: "/privacy-policy", permanent: true },
      { source: "/gdpr-compliance-for-remote-hiring/", destination: "/privacy-policy", permanent: true },
      { source: "/outsourcing-success-stories", destination: "/blog", permanent: true },
      { source: "/outsourcing-success-stories/", destination: "/blog", permanent: true },
      { source: "/outsource-to-india", destination: "/services/remote-employees-for-your-business", permanent: true },
      { source: "/outsource-to-india/", destination: "/services/remote-employees-for-your-business", permanent: true },

      /* ─── Case studies → /case-studies (301 permanent) ─── */
      {
        source: "/:slug(case-study-.*)",
        destination: "/case-studies",
        permanent: true,
      },

      /* ─── How It Works variations ─── */
      { source: "/how-it-works-remote-staffing", destination: "/how-it-works", permanent: true },
      { source: "/how-it-works-remote-staffing/", destination: "/how-it-works", permanent: true },

      /* ─── Catch remaining old blog posts with trailing slashes ─── */
      { source: "/best-remote-staffing-agency-for-remote-jobs", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/best-remote-staffing-agency-for-remote-jobs/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-services-zedtreeo", destination: "/services", permanent: true },
      { source: "/remote-staffing-services-zedtreeo/", destination: "/services", permanent: true },

      /* ─── NOINDEX posts — off-topic/thin → redirect to homepage ─── */
      { source: "/crypto-coins-and-financial-accounting-a-complete-business-guide", destination: "/", permanent: true },
      { source: "/crypto-coins-and-financial-accounting-a-complete-business-guide/", destination: "/", permanent: true },
      { source: "/irs-form-8832-llc-tax-classification-guide-2026", destination: "/", permanent: true },
      { source: "/irs-form-8832-llc-tax-classification-guide-2026/", destination: "/", permanent: true },
      { source: "/financial-markets-overview-trading-strategies-fund-management", destination: "/", permanent: true },
      { source: "/financial-markets-overview-trading-strategies-fund-management/", destination: "/", permanent: true },
      { source: "/risk-management-strategies-in-trading-and-fund-management", destination: "/", permanent: true },
      { source: "/risk-management-strategies-in-trading-and-fund-management/", destination: "/", permanent: true },
      { source: "/how-to-spell-bookkeeper", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/how-to-spell-bookkeeper/", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/environmental-impact-of-remote-work", destination: "/blog", permanent: true },
      { source: "/environmental-impact-of-remote-work/", destination: "/blog", permanent: true },
      { source: "/remote-work-and-sustainability-insights", destination: "/blog", permanent: true },
      { source: "/remote-work-and-sustainability-insights/", destination: "/blog", permanent: true },
      { source: "/bridging-the-digital-divide", destination: "/blog", permanent: true },
      { source: "/bridging-the-digital-divide/", destination: "/blog", permanent: true },
      { source: "/empowering-women-through-remote-work", destination: "/blog", permanent: true },
      { source: "/empowering-women-through-remote-work/", destination: "/blog", permanent: true },
      { source: "/how-remote-work-empowers-developing-regions-economically", destination: "/blog", permanent: true },
      { source: "/how-remote-work-empowers-developing-regions-economically/", destination: "/blog", permanent: true },
      { source: "/diversity-inclusion-in-remote-work-environments", destination: "/blog", permanent: true },
      { source: "/diversity-inclusion-in-remote-work-environments/", destination: "/blog", permanent: true },
      { source: "/remote-work-and-agile-practices", destination: "/blog/remote-work-agile-practices", permanent: true },
      { source: "/remote-work-and-agile-practices/", destination: "/blog/remote-work-agile-practices", permanent: true },
      { source: "/cybersecurity-future-challenges", destination: "/services/cyber-security-expert", permanent: true },
      { source: "/cybersecurity-future-challenges/", destination: "/services/cyber-security-expert", permanent: true },

      /* ─── MERGE posts — consolidate into stronger articles ─── */
      /* remote-staffing-guide already declared above — skipped duplicate */
      { source: "/the-state-of-remote-work-in-2024", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/the-state-of-remote-work-in-2024/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/analyzing-trends-in-remote-work-adoption", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/analyzing-trends-in-remote-work-adoption/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-trends-insights-from-hr-professionals", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-trends-insights-from-hr-professionals/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/the-future-of-remote-work-perspectives-from-experts", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/the-future-of-remote-work-perspectives-from-experts/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-work-insights-from-industry-leaders", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-work-insights-from-industry-leaders/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-work-and-productivity-a-research-report", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-work-and-productivity-a-research-report/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/economics-of-remote-work-market-trends-insights", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/economics-of-remote-work-market-trends-insights/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-insights-from-remote-employees", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/remote-staffing-insights-from-remote-employees/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/remote-staffing-report-country-by-country-comparison", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/remote-staffing-report-country-by-country-comparison/", destination: "/blog/outsourcing-costs", permanent: true },
      { source: "/remote-staffing-cost-savings-guide", destination: "/blog/how-remote-staffing-reduces-hiring-costs", permanent: true },
      { source: "/remote-staffing-cost-savings-guide/", destination: "/blog/how-remote-staffing-reduces-hiring-costs", permanent: true },

      /* ─── Remaining unmigrated blog posts → best-match articles ─── */
      { source: "/ai-content-generators-complete-guide-to-ai-text-image-code-writing-tools", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/ai-content-generators-complete-guide-to-ai-text-image-code-writing-tools/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/ai-vs-human-talent-why-businesses-still-need-remote-professionals", destination: "/blog/ai-vs-human-talent", permanent: true },
      { source: "/ai-vs-human-talent-why-businesses-still-need-remote-professionals/", destination: "/blog/ai-vs-human-talent", permanent: true },
      { source: "/become-remote-ai-prompt-engineer-2026", destination: "/services/virtual-assistants", permanent: true },
      { source: "/become-remote-ai-prompt-engineer-2026/", destination: "/services/virtual-assistants", permanent: true },
      { source: "/bookkeeper-synonyms-alternative-titles", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/bookkeeper-synonyms-alternative-titles/", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/bookkeeping-software-remote-bookkeeper-zedtreeo-2026", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/bookkeeping-software-remote-bookkeeper-zedtreeo-2026/", destination: "/services/virtual-assistant-for-bookkeeping", permanent: true },
      { source: "/budgeting-insights-smart-strategies-for-organizations", destination: "/blog/budgeting-insights", permanent: true },
      { source: "/budgeting-insights-smart-strategies-for-organizations/", destination: "/blog/budgeting-insights", permanent: true },
      { source: "/content-moderation-outsourcing-remote-bouncers-24x7", destination: "/blog/content-moderation-outsourcing", permanent: true },
      { source: "/content-moderation-outsourcing-remote-bouncers-24x7/", destination: "/blog/content-moderation-outsourcing", permanent: true },
      { source: "/cost-benefit-analysis-of-remote-staffing-solutions-in-finance", destination: "/blog/cost-benefit-remote-staffing-finance", permanent: true },
      { source: "/cost-benefit-analysis-of-remote-staffing-solutions-in-finance/", destination: "/blog/cost-benefit-remote-staffing-finance", permanent: true },
      { source: "/data-entry-security-best-practices", destination: "/blog/data-entry-outsourcing-guide", permanent: true },
      { source: "/data-entry-security-best-practices/", destination: "/blog/data-entry-outsourcing-guide", permanent: true },
      { source: "/essential-tips-for-thriving-as-a-contract-paralegal", destination: "/blog/contract-paralegal-guide", permanent: true },
      { source: "/essential-tips-for-thriving-as-a-contract-paralegal/", destination: "/blog/contract-paralegal-guide", permanent: true },
      { source: "/finance-accounting-outsourcing-benefits", destination: "/blog/cost-benefit-remote-staffing-finance", permanent: true },
      { source: "/finance-accounting-outsourcing-benefits/", destination: "/blog/cost-benefit-remote-staffing-finance", permanent: true },
      { source: "/freelance-bookkeeper-rates", destination: "/blog/freelance-bookkeeper-rates", permanent: true },
      { source: "/freelance-bookkeeper-rates/", destination: "/blog/freelance-bookkeeper-rates", permanent: true },
      { source: "/global-geopolitical-shifts-remote-staffing-2025", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/global-geopolitical-shifts-remote-staffing-2025/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/h-1b-visa-crisis-why-remote-staffing-is-the-smart-alternative-for-2025", destination: "/blog/h1b-visa-remote-staffing-alternative", permanent: true },
      { source: "/h-1b-visa-crisis-why-remote-staffing-is-the-smart-alternative-for-2025/", destination: "/blog/h1b-visa-remote-staffing-alternative", permanent: true },
      { source: "/hire-bookkeeper-quickbooks-guide", destination: "/blog/hire-bookkeeper-quickbooks-guide", permanent: true },
      { source: "/hire-bookkeeper-quickbooks-guide/", destination: "/blog/hire-bookkeeper-quickbooks-guide", permanent: true },
      { source: "/how-remote-staffing-improves-operational-efficiency", destination: "/blog/remote-staffing-operational-efficiency", permanent: true },
      { source: "/how-remote-staffing-improves-operational-efficiency/", destination: "/blog/remote-staffing-operational-efficiency", permanent: true },
      { source: "/how-remote-staffing-reduces-hiring-costs-by-90", destination: "/blog/how-remote-staffing-reduces-hiring-costs", permanent: true },
      { source: "/how-remote-staffing-reduces-hiring-costs-by-90/", destination: "/blog/how-remote-staffing-reduces-hiring-costs", permanent: true },
      /* how-remote-work-empowers-developing-regions-economically already declared above — skipped duplicate */
      { source: "/hybrid-staffing-models", destination: "/blog/hybrid-staffing-models", permanent: true },
      { source: "/hybrid-staffing-models/", destination: "/blog/hybrid-staffing-models", permanent: true },
      { source: "/hybrid-work-models-the-future-of-remote-staffing", destination: "/blog/hybrid-staffing-models", permanent: true },
      { source: "/hybrid-work-models-the-future-of-remote-staffing/", destination: "/blog/hybrid-staffing-models", permanent: true },
      { source: "/innovative-ways-to-lower-business-costs", destination: "/blog/reduce-business-costs-remote-staffing", permanent: true },
      { source: "/innovative-ways-to-lower-business-costs/", destination: "/blog/reduce-business-costs-remote-staffing", permanent: true },
      { source: "/lessons-in-crisis-management-for-remote-teams", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/lessons-in-crisis-management-for-remote-teams/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/llmops-explained-guide-2026", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/llmops-explained-guide-2026/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/managing-remote-healthcare-teams-effectively", destination: "/blog/managing-remote-healthcare-teams", permanent: true },
      { source: "/managing-remote-healthcare-teams-effectively/", destination: "/blog/managing-remote-healthcare-teams", permanent: true },
      { source: "/managing-time-zones-in-remote-work", destination: "/blog/managing-time-zones-remote-work", permanent: true },
      { source: "/managing-time-zones-in-remote-work/", destination: "/blog/managing-time-zones-remote-work", permanent: true },
      { source: "/medical-billing-virtual-assistant", destination: "/blog/medical-billing-virtual-assistant", permanent: true },
      { source: "/medical-billing-virtual-assistant/", destination: "/blog/medical-billing-virtual-assistant", permanent: true },
      { source: "/outsource-bookkeeping-india", destination: "/blog/outsource-bookkeeping-india", permanent: true },
      { source: "/outsource-bookkeeping-india/", destination: "/blog/outsource-bookkeeping-india", permanent: true },
      { source: "/rag-explained-guide", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/rag-explained-guide/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/reliable-staff-augmentation-services-market-analysis-2025", destination: "/blog/bpo-services", permanent: true },
      { source: "/reliable-staff-augmentation-services-market-analysis-2025/", destination: "/blog/bpo-services", permanent: true },
      { source: "/remote-ai-jobs-guide-2026", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/remote-ai-jobs-guide-2026/", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/remote-staffing-key-success-considerations", destination: "/blog/remote-staffing-success-factors", permanent: true },
      { source: "/remote-staffing-key-success-considerations/", destination: "/blog/remote-staffing-success-factors", permanent: true },
      { source: "/remote-staffing-solutions-for-underrepresented-communities", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-solutions-for-underrepresented-communities/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-trends-a-comprehensive-analysis", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-staffing-trends-a-comprehensive-analysis/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/remote-work-cybersecurity", destination: "/blog/remote-work-cybersecurity", permanent: true },
      { source: "/remote-work-cybersecurity/", destination: "/blog/remote-work-cybersecurity", permanent: true },
      { source: "/remote-work-pros-and-cons-for-employers", destination: "/blog/remote-work-pros-cons-employers", permanent: true },
      { source: "/remote-work-pros-and-cons-for-employers/", destination: "/blog/remote-work-pros-cons-employers", permanent: true },
      { source: "/remote-work-setup-guide-2026", destination: "/blog/remote-work-setup-guide", permanent: true },
      { source: "/remote-work-setup-guide-2026/", destination: "/blog/remote-work-setup-guide", permanent: true },
      { source: "/robotic-use-in-medical-transforming-healthcare-operations-with-remote-staffing", destination: "/services/revenue-cycle-management-staff", permanent: true },
      { source: "/robotic-use-in-medical-transforming-healthcare-operations-with-remote-staffing/", destination: "/services/revenue-cycle-management-staff", permanent: true },
      { source: "/strategies-for-business-continuity", destination: "/blog/business-continuity-remote-teams", permanent: true },
      { source: "/strategies-for-business-continuity/", destination: "/blog/business-continuity-remote-teams", permanent: true },
      { source: "/sustainable-remote-staffing-models-for-the-future", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/sustainable-remote-staffing-models-for-the-future/", destination: "/blog/best-remote-staffing-agencies", permanent: true },
      { source: "/top-5-reasons-businesses-are-turning-to-virtual-assistants", destination: "/blog/virtual-assistant-pricing", permanent: true },
      { source: "/top-5-reasons-businesses-are-turning-to-virtual-assistants/", destination: "/blog/virtual-assistant-pricing", permanent: true },
      { source: "/transform-your-legal-content-with-expert-legal-writers", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/transform-your-legal-content-with-expert-legal-writers/", destination: "/services/virtual-legal-staff", permanent: true },
      { source: "/virtual-bookkeeping-services", destination: "/blog/virtual-bookkeeping-services", permanent: true },
      { source: "/virtual-bookkeeping-services/", destination: "/blog/virtual-bookkeeping-services", permanent: true },
      { source: "/virtual-paralegal-assistants-why-every-law-firm-should-opt-for-them", destination: "/blog/virtual-paralegal-services", permanent: true },
      { source: "/virtual-paralegal-assistants-why-every-law-firm-should-opt-for-them/", destination: "/blog/virtual-paralegal-services", permanent: true },
      { source: "/virtual-staffing-ai-integration-human-expertise", destination: "/blog/ai-integrated-virtual-staffing", permanent: true },
      { source: "/virtual-staffing-ai-integration-human-expertise/", destination: "/blog/ai-integrated-virtual-staffing", permanent: true },
      { source: "/why-startups-smes-should-outsource-accounting", destination: "/blog/why-startups-smes-should-outsource-accounting", permanent: true },
      { source: "/why-startups-smes-should-outsource-accounting/", destination: "/blog/why-startups-smes-should-outsource-accounting", permanent: true },
      { source: "/work-from-home-ai-jobs-gpt-guide-2026", destination: "/blog/ai-vs-outsourcing", permanent: true },
      { source: "/work-from-home-ai-jobs-gpt-guide-2026/", destination: "/blog/ai-vs-outsourcing", permanent: true },

      /* Trailing slashes handled by Next.js trailingSlash: false (default) */
    ];
  },
};

export default nextConfig;
